### PR TITLE
Use provided scope for Flow deps in tests

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-component-base/49)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow-component-base/49#-LBtS2iU8LLELYUm3xaZ:-LBtaHEw2l6YazX-u4Vq:bsxfwfg) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

I think you need to resolve the conflict of the POM file. 

and one thoughts: 

the default profile, downloads the chromeDriver for test case. so when we are running the `mvn install -PrunTests`, will the chromeDriver be downloaded still?

</blockquote></details>

profiles are not mutually exclusive.
The active by default profile will always active.

---

*[pom.xml, line 59 at r1](https://reviewable.io/reviews/vaadin/flow-component-base/49#-LBtTpZqB1hsirtkO9nb:-LBtaRRo-RWs96EGHuhf:b-yf92vk) ([raw file](https://github.com/vaadin/flow-component-base/blob/e32194ca8beeb2f81d3ee5e27c84c80c060979df/pom.xml#L59)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

do we need this dependency here? why? looks like a potential burden for maintenance  
</blockquote></details>

Didn't touch this.

---

*[pom.xml, line 67 at r1](https://reviewable.io/reviews/vaadin/flow-component-base/49#-LBtTWWaEveBjK5XObRJ:-LBtaPxfEhnw_swZIYjS:b-yf92vk) ([raw file](https://github.com/vaadin/flow-component-base/blob/6cd0f7fe547a230435fae86f7ca1b8eafdfd9f90/pom.xml#L67)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

this repository is where we released flow,  instead of removing it, i think it just need to be renamed to `vaadin-prereleases`, as we still need it.
</blockquote></details>

Didn't touch this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-component-base/49)*

**Comment by ZheSun88** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow-component-base/49#-LBtS2iU8LLELYUm3xaZ:-LBthYq58-M0cOQxCI4d:b75ohmu) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

profiles are not mutually exclusive.
The active by default profile will always active.
</blockquote></details>

okay, great

build failed with 
``` 
Failed to execute goal on project flow-component-base: Could not resolve dependencies for project com.vaadin:flow-component-base:pom:1.0-SNAPSHOT: Could not find artifact com.vaadin:flow-client:jar:1.0-SNAPSHOT
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-component-base/49)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pom.xml, line 46 at r2](https://reviewable.io/reviews/vaadin/flow-component-base/49#-LBttwDo3_-2ZLeaft5D:-LBtv1Fz5ngE523ASlWk:b-896fix) ([raw file](https://github.com/vaadin/flow-component-base/blob/9a3716c510107ddad64ea6a5c3bf3d1e304176c0/pom.xml#L46)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

umm. do we need to move this? that is only for releasing the components.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-component-base/49)*

**Comment by ZheSun88** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-component-base/49#-:-LBtv8AeA2xa0kpOuQt8:bnfp4nl)*

**Pull request merged**
