### PR TITLE
Remove flow-test-utils from compile scope, fix dependencies errors.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-component-base/51)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

*[pom.xml, line 292 at r1](https://reviewable.io/reviews/vaadin/flow-component-base/51#-LC9pWVG679KXA8Mhtp0:-LC9pWVG679KXA8Mhtp1:bplu1nv) ([raw file](https://github.com/vaadin/flow-component-base/blob/d07805c8d1ac7cb61f708cbae1b897c5e91ea4e2/pom.xml#L292)):*
<details><summary><i alt="summary">Quoted 20 lines of code…</i></summary>

> ```
>         <dependency>
>             <groupId>com.vaadin</groupId>
>             <artifactId>flow-server</artifactId>
>             <version>${flow.version}</version>
>         </dependency>
>         <dependency>
>             <groupId>com.vaadin</groupId>
>             <artifactId>flow-client</artifactId>
>             <version>${flow.version}</version>
>         </dependency>
>         <dependency>
>             <groupId>com.vaadin</groupId>
>             <artifactId>flow-data</artifactId>
>             <version>${flow.version}</version>
>         </dependency>
>         <dependency>
>             <groupId>com.vaadin</groupId>
>             <artifactId>flow-html-components</artifactId>
>             <version>${flow.version}</version>
>         </dependency>
> ```
</details>



This revert back the fix that has been made to use `provided` scope for the components.
Those dependencies are transient so are inherited by every component.
And component should declare `provided` dependency instead of `compile`.

---

*[pom.xml, line 302 at r1](https://reviewable.io/reviews/vaadin/flow-component-base/51#-LC9pwu729T_5MEEBN7V:-LC9pwu729T_5MEEBN7W:b-ub4duw) ([raw file](https://github.com/vaadin/flow-component-base/blob/d07805c8d1ac7cb61f708cbae1b897c5e91ea4e2/pom.xml#L302)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         <dependency>
>             <groupId>com.vaadin</groupId>
>             <artifactId>flow-test-util</artifactId>
>             <version>${flow.version}</version>
>             <scope>test</scope>
>         </dependency>
> ```
</details>


The `test`  scope is not transient.
So I'm not sure that component's build won't  fail with this change.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-component-base/51)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pom.xml, line 292 at r1](https://reviewable.io/reviews/vaadin/flow-component-base/51#-LC9pWVG679KXA8Mhtp0:-LC9wLAv3jlJfa7kb3MG:bhu1vgb) ([raw file](https://github.com/vaadin/flow-component-base/blob/d07805c8d1ac7cb61f708cbae1b897c5e91ea4e2/pom.xml#L292)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>         <dependency>
>             <groupId>com.vaadin</groupId>
>             <artifactId>flow-server</artifactId>
>             <version>${flow.version}</version>
>         </dependency>
>         <dependency>
>             <groupId>com.vaadin</groupId>
>             <artifactId>flow-client</artifactId>
>             <version>${flow.version}</version>
>         </dependency>
>         <dependency>
>             <groupId>com.vaadin</groupId>
>             <artifactId>flow-data</artifactId>
>             <version>${flow.version}</version>
>         </dependency>
>         <dependency>
>             <groupId>com.vaadin</groupId>
>             <artifactId>flow-html-components</artifactId>
>             <version>${flow.version}</version>
>         </dependency>
> ```


This revert back the fix that has been made to use `provided` scope for the components.
Those dependencies are transient so are inherited by every component.
And component should declare `provided` dependency instead of `compile`.
</blockquote></details>

I haven't changed the scope of them: the default one is `compile` and, before the change, they've had it specified explicitly for some reason: `<scope>compile</scope>`, I've just removed the redundant declaration, so I don't understand which change it reverts.

Should those dependencies have `provided` scope instead?

---

*[pom.xml, line 302 at r1](https://reviewable.io/reviews/vaadin/flow-component-base/51#-LC9pwu729T_5MEEBN7V:-LC9wdtKCRwJqqgCFj1x:bfenjo9) ([raw file](https://github.com/vaadin/flow-component-base/blob/d07805c8d1ac7cb61f708cbae1b897c5e91ea4e2/pom.xml#L302)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>         <dependency>
>             <groupId>com.vaadin</groupId>
>             <artifactId>flow-test-util</artifactId>
>             <version>${flow.version}</version>
>             <scope>test</scope>
>         </dependency>
> ```

The `test`  scope is not transient.
So I'm not sure that component's build won't  fail with this change.
</blockquote></details>

This pom has `<packaging>pom</packaging>` so nothing is transitive for the project anyway.
Afaik, each component's pom has this pom as a parent, so they will get this dependency in test scope.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-component-base/51)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pom.xml, line 292 at r1](https://reviewable.io/reviews/vaadin/flow-component-base/51#-LC9pWVG679KXA8Mhtp0:-LCASrGWBaKl7JfBo2yr:bk7tqht) ([raw file](https://github.com/vaadin/flow-component-base/blob/d07805c8d1ac7cb61f708cbae1b897c5e91ea4e2/pom.xml#L292)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I haven't changed the scope of them: the default one is `compile` and, before the change, they've had it specified explicitly for some reason: `<scope>compile</scope>`, I've just removed the redundant declaration, so I don't understand which change it reverts.

Should those dependencies have `provided` scope instead?
</blockquote></details>

The scope is not changed.
But you have moved them out of the profile.
Now components have `compile` scope.

Every component  should have `provided` scope for flow (and they have).
The problem is that we also need `compile` scope to run IT tests.
That's why there is a default profile where they are declared.
It allows ( I hope and suppose) to have `provided` scope (dep is declared in every component)
when component is used as a dependency by itself and
`compile` scope when IT test is executed.

---

*[pom.xml, line 302 at r1](https://reviewable.io/reviews/vaadin/flow-component-base/51#-LC9pwu729T_5MEEBN7V:-LCATrewCZz0qHlyBiYi:b7alfhj) ([raw file](https://github.com/vaadin/flow-component-base/blob/d07805c8d1ac7cb61f708cbae1b897c5e91ea4e2/pom.xml#L302)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

This pom has `<packaging>pom</packaging>` so nothing is transitive for the project anyway.
Afaik, each component's pom has this pom as a parent, so they will get this dependency in test scope.
</blockquote></details>

OK.........
But please check for some component that it works as expected anyway.
If `test` scope works then it may be kept outside of the profile as in this PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-component-base/51)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pom.xml, line 292 at r1](https://reviewable.io/reviews/vaadin/flow-component-base/51#-LC9pWVG679KXA8Mhtp0:-LCAb9PdAfxSAllxhVRU:bsz2cd2) ([raw file](https://github.com/vaadin/flow-component-base/blob/d07805c8d1ac7cb61f708cbae1b897c5e91ea4e2/pom.xml#L292)):*
> But you have moved them out of the profile.
> Now components have compile scope.


The profile I've moved the out of is active by default, which means that the dependencies are there anyway.
Also, the profile we're talking about was used just for downloading Chrome drivers, so I suspect that putting the dependencies there might be an error.

---

*[pom.xml, line 302 at r1](https://reviewable.io/reviews/vaadin/flow-component-base/51#-LC9pwu729T_5MEEBN7V:-LCAb-G59VSoR8buhlfI:b9nio8a) ([raw file](https://github.com/vaadin/flow-component-base/blob/d07805c8d1ac7cb61f708cbae1b897c5e91ea4e2/pom.xml#L302)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

OK.........
But please check for some component that it works as expected anyway.
If `test` scope works then it may be kept outside of the profile as in this PR.
</blockquote></details>

Have checked a number of projects: tests run, no compilation errors.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-component-base/51)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 292 at r1](https://reviewable.io/reviews/vaadin/flow-component-base/51#-LC9pWVG679KXA8Mhtp0:-LCCjipv8NfkwPaUSw17:b-ecspiw) ([raw file](https://github.com/vaadin/flow-component-base/blob/d07805c8d1ac7cb61f708cbae1b897c5e91ea4e2/pom.xml#L292)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> But you have moved them out of the profile.
> Now components have compile scope.


The profile I've moved the out of is active by default, which means that the dependencies are there anyway.
Also, the profile we're talking about was used just for downloading Chrome drivers, so I suspect that putting the dependencies there might be an error.

</blockquote></details>

Are you sure that dependencies from active profile dependencies transitively goes to modules which depends on this module ?

If so then I made a mistake when extracted them out of the dedicated profile which is not active by default and they should be moved back.

https://github.com/vaadin/flow-component-base/commit/4359d25890838dab01e2ba30cd39fc0bd2375a5f

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-component-base/51)*

**Comment by denis-anisimov** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 292 at r1](https://reviewable.io/reviews/vaadin/flow-component-base/51#-LC9pWVG679KXA8Mhtp0:-LCCpVL63nD17qX2x6DA:bxe2shi) ([raw file](https://github.com/vaadin/flow-component-base/blob/d07805c8d1ac7cb61f708cbae1b897c5e91ea4e2/pom.xml#L292)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Are you sure that dependencies from active profile dependencies transitively goes to modules which depends on this module ?

If so then I made a mistake when extracted them out of the dedicated profile which is not active by default and they should be moved back.

https://github.com/vaadin/flow-component-base/commit/4359d25890838dab01e2ba30cd39fc0bd2375a5f
</blockquote></details>

Couldn't wait, sorry. Did it by myself. I need it immediately.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-component-base/51)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-component-base/51#-:-LCCpbHCADGu6Oqcksc4:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
*[pom.xml, line 292 at r1](https://reviewable.io/reviews/vaadin/flow-component-base/51#-LC9pWVG679KXA8Mhtp0:-LCCwLAY1HEAo-v0uxXh:b-8fx2u7) ([raw file](https://github.com/vaadin/flow-component-base/blob/d07805c8d1ac7cb61f708cbae1b897c5e91ea4e2/pom.xml#L292)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Couldn't wait, sorry. Did it by myself. I need it immediately.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-component-base/51)*

**Pull request merged**
