### PR TITLE
Making component projects compatible with JDK 9+

### PR DESCRIPTION
**Pull request by mstahv**
Individual component projects still need to start using this version (they currently seem to refer 1.2-SNAPSHOT).

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-component-base/113)

### CODE REVIEW

**Comment by mstahv** [comment]
@denis-anisimov if the versions are inline, 

 * I can see the version next to the plugin configuration
 * IDE helps me to find out the latest version of it
 * the pom.xml is shorter

I also don't see why (especially plugin versions) should be as variables. Do you configure special values for those when running builds?

**Comment by denis-anisimov** [comment]
I'm not sure about other versions but at least jetty version is used in the components `pom.xml`.

See e.g. https://github.com/vaadin/vaadin-grid-flow/blob/master/pom.xml#L270

So:
- let's don't do several things at once in one patch
- `jetty.verson`  can't be removed from properties at all. It will break component builds.
- It might be that we should not use versions as properties but this needs a separate PR and first all components should be reviewed against those changes in their parent `flow-component-base`.

**Comment by mstahv** [comment]
Is there some reason to specify the plugin version there in vaadin-grid-flow? I created a PR to remove that: https://github.com/vaadin/vaadin-grid-flow/pull/456

I generally agree that one PR/change for one feature, but the feature for me was not the Java 9+ compatibility. It would cause now a lot of wasted time for both me and somebody reviewing that stuff, so it really isn't tempting to start splitting this (still rather small change) into two. 😥

**Comment by denis-anisimov** [comment]
I don't know about any specific reason to have jetty version in grid repo.
It's just done in the way how it's done. It's kind of result of long evolution with absence of proper clean up .

But this is a question for `Grid` . Not here.

You may not remove `jetty.version` here because it affects grid for now.

Also I'm not sure that `Grid`  the only one component which requires this or other properties.

I don't see a strong reason to have property removal in this PR.
If you return them back then other changes still makes sense and also are not affected by the removal.
So it will fix the JDK 9 compatibility without properties removal.

Having several unrelated changes in one PR is proven as error prone way.

I understand that it's easier and I do sometimes the same.
But here I see definitely an issue with such removal at least with `Grid`.
And it might be that there can be other places in a huge number of component repos that we have.
So we may not remove all properties here before every component is checked for them.

I would suggest to avoid such changes in this PR. Keep only meaningful changes. Goes through all components repo and clean up them first. Then make a separate PR for this repo when all components repo are ready for this change.

**Comment by denis-anisimov** [comment]
Otherwise: I still need to go through all components repo by myself and check that this PR doesn't break them.
That will require some time. As a result review will take quite long time.

**Comment by mstahv** [comment]
We don't have a build that builds all component integrations? Executing that once against this change should check if the jetty.version property is still in use.

They are all checked as git subprojects here, but I guess not built by this. 🤔

**Comment by mstahv** [comment]
Tested by adding this to this project:

    <modules>
        <module>vaadin-checkbox-flow</module>
        <module>vaadin-form-layout-flow</module>
        <module>vaadin-notification-flow</module>
        <module>vaadin-tabs-flow</module>
        <module>vaadin-combo-box-flow</module>
        <module>vaadin-grid-flow</module>
        <module>vaadin-ordered-layout-flow</module>
        <module>vaadin-text-field-flow</module>
        <module>vaadin-context-menu-flow</module>
        <module>vaadin-icons-flow</module>
        <module>vaadin-progress-bar-flow</module>
        <module>vaadin-upload-flow</module>
        <module>vaadin-date-picker-flow</module>
        <module>vaadin-iron-list-flow</module>
        <module>vaadin-radio-button-flow</module>
        <module>vaadin-button-flow</module>
        <module>vaadin-dialog-flow</module>
        <module>vaadin-list-box-flow</module>
        <module>vaadin-split-layout-flow</module>
    </modules>


It looks like vaadin-text-field-flow also has the obsolete jetty version.

**Comment by mstahv** [comment]
This PR removes the usage of obsolete jetty property from vaadin-text-field-flow : https://github.com/vaadin/vaadin-text-field-flow/pull/124

**Comment by mstahv** [comment]
It might still though be that some modules are not updated to 1.3-SNAPSHOT 🤔

**Comment by denis-anisimov** [comment]
> We don't have a build that builds all component integrations? Executing that once against this change should check if the jetty.version property is still in use.
> 
> They are all checked as git subprojects here, but I guess not built by this. 🤔

I think we don't have such build.

**Comment by mstahv** [comment]
@denis-anisimov I created PRs to remove the obsolete version and to update to 1.3-SNAPSHOT for those projects

**Comment by denis-anisimov** [comment]
There is one more new project which I wasn't aware of :
https://github.com/vaadin/vaadin-time-picker-flow/blob/master/pom.xml#L198

**Comment by mstahv** [comment]
Why was this assigned to me?

**Comment by mstahv** [comment]
ping!

I'd really like to get this in. It is disturbing to always downgrade to legacy JDK when starting to work on some Vaadin component.

**Comment by denis-anisimov** [comment]
There are conflicts which needs to be resolved manually.
Could you please rebase this PR.

**Comment by mstahv** [comment]
There was no conflicts last time I worked on this 😤

**Comment by caalador** [comment]
Due to huge refactoring changes to the base and components I'm closing this PR.

If the issue still remains please make a PR for the older and newer branches as the
function of those might differ considerably.

**Pull request closed without merging**
