### PR TITLE
update submodules 

### PR DESCRIPTION
**Pull request by ZheSun88**
---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-component-base/41)

### CODE REVIEW

**Comment by pleku** [comment]
Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 39 at r2](https://reviewable.io:443/reviews/vaadin/flow-component-base/41#-L2dZuu5ovHvNRCxifKx:-L2dZuu5ovHvNRCxifKy:bwqo6x4) ([raw file](https://github.com/vaadin/flow-component-base/blob/4f5dbb5202fc4bfbd6a5e9d5bc3f8916acf63736/README.md#L39)):*
> ```Markdown
> or using `git submodule foreach git pull origin master` to update all the submodules in the project
> 
> For more submodule usage, you can also check the tutorial [here](https://git-scm.com/docs/git-submodule)
> ```

I don't think this is the way it should be done.

I made a commit a while back that addresses this in a much better way than what described here, but I've forgot to make a PR for it since it was waiting for the previous patch to go in.

Can you please remove this part so I can make a PR for it, it is in https://github.com/vaadin/flow-component-base/commit/a530cd14ddca8949c8f096d8cac1d05fefbc0148 and makes this documentation a lot simpler.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-component-base/41)*

**Comment by ZheSun88** [comment]
Review status: 0 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 39 at r2](https://reviewable.io:443/reviews/vaadin/flow-component-base/41#-L2dZuu5ovHvNRCxifKx:-L2dcqoSuhKxM9Iv8jlN:be9kify) ([raw file](https://github.com/vaadin/flow-component-base/blob/4f5dbb5202fc4bfbd6a5e9d5bc3f8916acf63736/README.md#L39)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I don't think this is the way it should be done.

I made a commit a while back that addresses this in a much better way than what described here, but I've forgot to make a PR for it since it was waiting for the previous patch to go in.

Can you please remove this part so I can make a PR for it, it is in https://github.com/vaadin/flow-component-base/commit/a530cd14ddca8949c8f096d8cac1d05fefbc0148 and makes this documentation a lot simpler.
</blockquote></details>

okay, i have reverted this part. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-component-base/41)*

**Comment by SomeoneToIgnore** [comment]
Most probably it needs to be updated again. But up to you.

---

Reviewed 17 of 18 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-component-base/41#-:-L2eDV8Isr2EoTonbg18:bv2um0g)*

**Comment by ZheSun88** [comment]
In fact, i think i should dump this patch... and open a new one after we updated everything.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-component-base/41#-:-L2eE2NRvOfgSLBLcSWN:b-y2u3bv)*

**Comment by SomeoneToIgnore** [comment]
Yes, that was my point.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-component-base/41#-:-L2eEHHTIPSxv8u90VD_:bchlmd4)*

**Comment by ZheSun88** [comment]
Then let us just close it...

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-component-base/41#-:-L2eEtTyS1sw8MgwdBh5:b-ftygm2)*

**Pull request closed without merging**
